### ISSUE TITLE
BRTI (Bitcoin Real Time Index)

### ISSUE THREAD

**Issue by Alexmarch1** [CryptoFacilities/REST-v3-CSharp#1]
Hi. I want to get a BRTI index[https://www.cryptofacilities.com/indices]. But in the code I did not find an implementation. How can I get it?

**Comment by CryptoAdmin** [comment]
Hi, please use the getTickers() example which gives you data for all currently listed contracts and indices. (https://www.cryptofacilities.com/resources/hc/en-us/articles/360000528513-Tickers)

**Comment by Alexmarch1** [comment]
Thank you very much you helped me a lot.
Now I know that to get a BRTI I need to contact this address. (https://www.cryptofacilities.com/derivatives/api/v3/tickers?)
// get tickers
result = methods.getTickers ();
But the problem is how often can I contact?
Is there any way to sign up for an automatic update and not fill up the server with requests.

**Comment by CryptoAdmin** [comment]
You are welcome. You can have a look [here](https://www.cryptofacilities.com/resources/hc/en-us/articles/360000575894-Ticker). The examples are currently only in [python](https://github.com/CryptoFacilities/WebSocket-v1-Python). You will need to subscribe to feed: ticker and utilize the field **index**.

**Comment by Alexmarch1** [comment]
{"symbol":"in_xbtusd","last":**6425,**"lastTime":"2018-10-03T09:52:08.000Z"}
Thank you, I have a final question, why do index data provide without double precision?

**Comment by CryptoAdmin** [comment]
The value is rounded to the ticksize of the instruments that we are currently are listing.

**Comment by Alexmarch1** [comment]
Is it possible to get the exact value?
